name: Glog.AI Scan

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  security-events: write
  issues: write

jobs:
  glog-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Checkout glog-action repository
        uses: actions/checkout@v6
        with:
          repository: glogai/glog-action
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/glog-action
          ref: main

      - name: Run Glog.AI
        uses: ./.github/glog-action
        with:
          lang: 'go,javascript'
          upload: 'true'
          client: 'test'
          env: 'dev'
          ignore: 'template/js/vendor/**,template/Karma Shop-doc/**,template/js/gmaps.min.js,template/js/ion.rangeSlider.js,template/js/jquery.ajaxchimp.min.js,template/js/jquery.magnific-popup.min.js'
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
